-- 1. Create Store_Products Table
CREATE TABLE "Store_Products" (
    "Product_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "Name" TEXT NOT NULL,
    "Category" TEXT NOT NULL,
    "Base_Price" REAL NOT NULL DEFAULT 0.0,
    "Image_Url" TEXT,
    "Description" TEXT,
    "Created_At" TIMESTAMPTZ DEFAULT NOW(),
    "Updated_At" TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE "Store_Products" ENABLE ROW LEVEL SECURITY;

-- Policy: Users can manage their own products
CREATE POLICY "Users can manage their own Store Products" ON "Store_Products" 
FOR ALL USING (auth.uid() = user_id);

-- Policy: Anyone can read products (for the public storefront)
CREATE POLICY "Public can read Store Products" ON "Store_Products" 
FOR SELECT USING (true);
