-- SUPABASE MIGRATION SCHEMA FOR CLOVER
-- This file translates the local SQLite database into a Multi-Tenant PostgreSQL database.
-- It adds a `user_id` to every table so multiple users can have their own isolated CRM.
-- Instructions: Paste this entire script into the Supabase SQL Editor and hit "Run".

-- 1. Create Contacts Table
CREATE TABLE Contacts (
    Contact_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Name TEXT NOT NULL,
    Email TEXT,
    Phone TEXT,
    Lead_Source TEXT
);
ALTER TABLE Contacts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Contacts" ON Contacts FOR ALL USING (auth.uid() = user_id);

-- 2. Create Inquiries Table
CREATE TABLE Inquiries (
    Inquiry_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Contact_ID BIGINT NOT NULL REFERENCES Contacts(Contact_ID) ON DELETE CASCADE,
    Service_Type TEXT,
    Event_Date TEXT,
    Pipeline_Stage TEXT DEFAULT 'New Inquiry',
    Estimated_Value REAL DEFAULT 0.0
);
ALTER TABLE Inquiries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Inquiries" ON Inquiries FOR ALL USING (auth.uid() = user_id);

-- 3. Create Communications Table
CREATE TABLE Communications (
    Comm_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Inquiry_ID BIGINT NOT NULL REFERENCES Inquiries(Inquiry_ID) ON DELETE CASCADE,
    Last_Contact_Date TEXT,
    Last_Contact_By TEXT,
    Proposal_Link TEXT,
    Message TEXT
);
ALTER TABLE Communications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Communications" ON Communications FOR ALL USING (auth.uid() = user_id);

-- 4. Create Reminders Table
CREATE TABLE Reminders (
    Reminder_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Inquiry_ID BIGINT NOT NULL REFERENCES Inquiries(Inquiry_ID) ON DELETE CASCADE,
    Reminder_Type TEXT,
    Due_Date TEXT,
    Notes TEXT,
    Is_Completed INTEGER DEFAULT 0,
    Channel TEXT DEFAULT 'Email',
    Sent_At TEXT DEFAULT NULL
);
ALTER TABLE Reminders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Reminders" ON Reminders FOR ALL USING (auth.uid() = user_id);

-- 5. Create AppConfig Table (Settings)
CREATE TABLE AppConfig (
    Config_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE, -- One config per user
    Company_Name TEXT,
    Admin_Email TEXT,
    Access_Pin TEXT,
    Google_Client_ID TEXT,
    Google_Client_Secret TEXT,
    Google_Refresh_Token TEXT,
    Email_User TEXT DEFAULT '',
    Email_Pass TEXT DEFAULT '',
    Business_Logo TEXT DEFAULT '',
    Business_Address TEXT DEFAULT '',
    Email_Settings TEXT DEFAULT '{}',
    Twilio_Account_SID TEXT DEFAULT '',
    Twilio_Auth_Token TEXT DEFAULT '',
    Twilio_Phone_Number TEXT DEFAULT ''
);
ALTER TABLE AppConfig ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own AppConfig" ON AppConfig FOR ALL USING (auth.uid() = user_id);

-- 6. Create EmailTemplates Table
CREATE TABLE EmailTemplates (
    Template_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Title TEXT NOT NULL,
    Subject TEXT NOT NULL,
    Body TEXT NOT NULL
);
ALTER TABLE EmailTemplates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own EmailTemplates" ON EmailTemplates FOR ALL USING (auth.uid() = user_id);

-- 7. Create Invoices and Invoice Items Tables
CREATE TABLE Invoices (
    Invoice_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Inquiry_ID BIGINT NOT NULL REFERENCES Inquiries(Inquiry_ID) ON DELETE CASCADE,
    Issue_Date TEXT,
    Due_Date TEXT,
    Status TEXT DEFAULT 'Draft',
    Total_Amount REAL DEFAULT 0.0
);
ALTER TABLE Invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Invoices" ON Invoices FOR ALL USING (auth.uid() = user_id);

CREATE TABLE Invoice_Items (
    Item_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Invoice_ID BIGINT NOT NULL REFERENCES Invoices(Invoice_ID) ON DELETE CASCADE,
    Description TEXT,
    Quantity INTEGER DEFAULT 1,
    Price REAL DEFAULT 0.0
);
ALTER TABLE Invoice_Items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Invoice Items" ON Invoice_Items FOR ALL USING (auth.uid() = user_id);

-- 8. Create Contracts Table
CREATE TABLE Contracts (
    Contract_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Inquiry_ID BIGINT NOT NULL REFERENCES Inquiries(Inquiry_ID) ON DELETE CASCADE,
    Contract_Text TEXT,
    Status TEXT DEFAULT 'Draft',
    Sent_Date TEXT,
    Signed_Date TEXT,
    Sign_Token TEXT,
    Client_Signature TEXT,
    Provider_Signature TEXT,
    Signers TEXT,
    Contract_Title TEXT
);
ALTER TABLE Contracts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Contracts" ON Contracts FOR ALL USING (auth.uid() = user_id);

-- 9. Create Drafts and Templates Tables
CREATE TABLE Contract_Templates (
    Template_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Name TEXT NOT NULL,
    Content TEXT NOT NULL,
    Created_At TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE Contract_Templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Contract Templates" ON Contract_Templates FOR ALL USING (auth.uid() = user_id);

CREATE TABLE Contract_Drafts (
    Draft_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Title TEXT DEFAULT 'Untitled Contract',
    Content TEXT NOT NULL,
    Signers TEXT DEFAULT '[]',
    Status TEXT DEFAULT 'Draft',
    Created_At TIMESTAMPTZ DEFAULT NOW(),
    Updated_At TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE Contract_Drafts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Contract Drafts" ON Contract_Drafts FOR ALL USING (auth.uid() = user_id);

CREATE TABLE Invoice_Drafts (
    Draft_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Title TEXT DEFAULT 'Untitled Invoice',
    Content TEXT NOT NULL,
    Line_Items TEXT DEFAULT '[]',
    Status TEXT DEFAULT 'Draft',
    Client_Name TEXT DEFAULT '',
    Client_Email TEXT DEFAULT '',
    Due_Date TEXT DEFAULT '',
    Created_At TIMESTAMPTZ DEFAULT NOW(),
    Updated_At TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE Invoice_Drafts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Invoice Drafts" ON Invoice_Drafts FOR ALL USING (auth.uid() = user_id);

CREATE TABLE Invoice_Templates (
    Template_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Name TEXT NOT NULL,
    Content TEXT NOT NULL,
    Created_At TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE Invoice_Templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Invoice Templates" ON Invoice_Templates FOR ALL USING (auth.uid() = user_id);

-- 10. Create Packages and Sessions Tables
CREATE TABLE Sessions (
    Session_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Service_Type TEXT NOT NULL,
    Session_Type TEXT NOT NULL,
    Created_At TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE Sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Sessions" ON Sessions FOR ALL USING (auth.uid() = user_id);

CREATE TABLE Packages (
    Package_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Session_ID BIGINT REFERENCES Sessions(Session_ID) ON DELETE CASCADE,
    Name TEXT NOT NULL,
    Duration TEXT,
    Items TEXT,
    Description TEXT,
    Price REAL DEFAULT 0.0,
    Created_At TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE Packages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Packages" ON Packages FOR ALL USING (auth.uid() = user_id);

-- 11. Create Booking Funnel Tables
CREATE TABLE Questionnaire_Templates (
    Template_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Name TEXT NOT NULL,
    Created_At TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE Questionnaire_Templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Questionnaire Templates" ON Questionnaire_Templates FOR ALL USING (auth.uid() = user_id);

CREATE TABLE Questionnaire_Fields (
    Field_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    Label TEXT NOT NULL,
    Type TEXT NOT NULL,
    Options TEXT,
    Is_Required BOOLEAN DEFAULT TRUE,
    Order_Index INTEGER DEFAULT 0,
    Template_ID BIGINT REFERENCES Questionnaire_Templates(Template_ID) ON DELETE CASCADE
);
ALTER TABLE Questionnaire_Fields ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Questionnaire Fields" ON Questionnaire_Fields FOR ALL USING (auth.uid() = user_id);

CREATE TABLE Booking_Settings (
    Setting_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE, -- One row per user
    Contract_Template_ID BIGINT,
    Questionnaire_Template_ID BIGINT,
    Step1_Title TEXT DEFAULT 'Choose Your Experience',
    Step1_Subtitle TEXT DEFAULT 'Select the collection that perfectly fits your day.',
    Step2_Title TEXT DEFAULT 'Tell Us About Your Day',
    Step2_Subtitle TEXT DEFAULT 'Help us prepare the perfect agreement for your event.',
    Step3_Title TEXT DEFAULT 'Review & Sign Your Contract',
    Step3_Subtitle TEXT DEFAULT 'Please fill out any required fields and sign the agreement below.',
    Step4_Title TEXT DEFAULT 'Complete Your Booking',
    Step4_Subtitle TEXT DEFAULT 'Secure your date by submitting the 50% retainer.',
    Addons TEXT DEFAULT '[]',
    Payment_Methods TEXT DEFAULT '[]',
    Confirmation_Title TEXT DEFAULT 'Booking Confirmed!',
    Confirmation_Message TEXT DEFAULT 'Your deposit has been received and your contract is securely signed. We are officially locked in!'
);
ALTER TABLE Booking_Settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own Booking Settings" ON Booking_Settings FOR ALL USING (auth.uid() = user_id);

-- 12. Create Auth Trigger for new Users
-- Automatically create an AppConfig and Booking_Settings row when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.AppConfig (user_id) VALUES (new.id);
  INSERT INTO public.Booking_Settings (user_id) VALUES (new.id);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
