directories:
  output: dist-desktop
  buildResources: build
appId: com.epicmanagement.crm
productName: EPIC Management CRM
win:
  target: nsis
files:
  - filter:
      - main.js
      - package.json
      - .next/standalone/**/*
extraResources:
  - from: .next/static
    to: app/.next/static
  - from: public
    to: app/public
electronVersion: 42.0.1
