-- Add JSON columns to Inquiries for Questionnaire Data and Milestones
ALTER TABLE "Inquiries"
ADD COLUMN IF NOT EXISTS "Questionnaire_Data" JSONB,
ADD COLUMN IF NOT EXISTS "Deliverable_Milestones" JSONB;

-- Add Brand Color to AppConfig
ALTER TABLE "AppConfig"
ADD COLUMN IF NOT EXISTS "Brand_Color" TEXT DEFAULT '#0f172a';

-- Create Deliverables table
CREATE TABLE IF NOT EXISTS "Deliverables" (
  "Deliverable_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  "Inquiry_ID" BIGINT NOT NULL REFERENCES "Inquiries"("Inquiry_ID") ON DELETE CASCADE,
  "Title" TEXT NOT NULL,
  "Link_URL" TEXT,
  "Description" TEXT,
  "Added_Date" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Deliverables
ALTER TABLE "Deliverables" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own deliverables" 
ON "Deliverables" 
FOR ALL USING (auth.uid() = user_id);

-- Refresh schema cache
NOTIFY pgrst, 'reload schema';
