ALTER TABLE "Portrait_Settings"
ADD COLUMN IF NOT EXISTS "Hero_Headline" TEXT,
ADD COLUMN IF NOT EXISTS "Hero_Subheadline" TEXT,
ADD COLUMN IF NOT EXISTS "About_Text" TEXT,
ADD COLUMN IF NOT EXISTS "Session_Types" TEXT,
ADD COLUMN IF NOT EXISTS "Retainer_Amount" NUMERIC;
